all: BiTree IntervelLevel BTDepth PreInCreate

BiTree: BiTree.c
	gcc BiTree.c  -lm -o  ./out/BiTree

IntervelLevel: IntervelLevel.c
	gcc IntervelLevel.c -lm -o ./out/IntervelLevel

BTDepth: BTDepth.c
	gcc BTDepth.c -lm -o ./out/BTDepth

PreInCreate: PreInCreate.c
	gcc PreInCreate.c -lm -o ./out/PreInCreate

clean:
	rm -rf ./out/*