all: BiTree IntervelLevel BTDepth PreInCreate IsCompleteTree DsonNodes SwapTree PreK DelX PrintParents Ancestor BTWidth Pre2Post Tree2List SimilarTree WPL Tree2Exp

BiTree: BiTree.c
	gcc BiTree.c  -lm -o  ./out/BiTree

IntervelLevel: IntervelLevel.c
	gcc IntervelLevel.c -lm -o ./out/IntervelLevel

BTDepth: BTDepth.c
	gcc BTDepth.c -lm -o ./out/BTDepth

PreInCreate: PreInCreate.c
	gcc PreInCreate.c -lm -o ./out/PreInCreate

IsCompleteTree: IsCompleteTree.c
	gcc IsCompleteTree.c -lm -o ./out/IsCompleteTree

DsonNodes: DsonNodes.c
	gcc DsonNodes.c -lm -o ./out/DsonNodes

SwapTree: SwapTree.c
	gcc SwapTree.c -lm -o ./out/SwapTree

PreK: PreK.c
	gcc PreK.c -lm -o ./out/PreK

DelX: DelX.c
	gcc DelX.c -lm -o ./out/DelX

PrintParents: PrintParents.c
	gcc PrintParents.c -lm -o ./out/PrintParents

Ancestor: Ancestor.c
	gcc Ancestor.c -lm -o ./out/Ancestor

BTWidth: BTWidth.c
	gcc BTWidth.c -lm -o ./out/BTWidth

Pre2Post: Pre2Post.c
	gcc Pre2Post.c -lm -o ./out/Pre2Post

Tree2List: Tree2List.c
	gcc Tree2List.c -lm -o ./out/Tree2List

SimilarTree: SimilarTree.c
	gcc SimilarTree.c -lm -o ./out/SimilarTree

WPL: WPL.c
	gcc WPL.c -lm -o ./out/WPL

Tree2Exp: Tree2Exp.c
	gcc Tree2Exp.c -lm -o ./out/Tree2Exp

clean:
	rm -rf ./out/*