all: BiTree IntervelLevel BTDepth PreInCreate IsCompleteTree DsonNodes SwapTree PreK

BiTree: BiTree.c
	gcc BiTree.c  -lm -o  ./out/BiTree

IntervelLevel: IntervelLevel.c
	gcc IntervelLevel.c -lm -o ./out/IntervelLevel

BTDepth: BTDepth.c
	gcc BTDepth.c -lm -o ./out/BTDepth

PreInCreate: PreInCreate.c
	gcc PreInCreate.c -lm -o ./out/PreInCreate

IsCompleteTree: IsCompleteTree.c
	gcc IsCompleteTree.c -lm -o ./out/IsCompleteTree

DsonNodes: DsonNodes.c
	gcc DsonNodes.c -lm -o ./out/DsonNodes

SwapTree: SwapTree.c
	gcc SwapTree.c -lm -o ./out/SwapTree

PreK: PreK.c
	gcc PreK.c -lm -o ./out/PreK

clean:
	rm -rf ./out/*