all: LinkList Delx Delx2 ReversePrint DelMin ReverseLink

LinkList: LinkList.c
	gcc -o ./out/LinkList LinkList.c

Delx: Delx.c
	gcc -o ./out/Delx Delx.c

Delx2: Delx2.c
	gcc -o ./out/Delx2 Delx2.c

ReversePrint: ReversePrint.c
	gcc -o ./out/ReversePrint ReversePrint.c

DelMin:  DelMin.c
	gcc -o ./out/DelMin DelMin.c

ReverseLink: ReverseLink.c
	gcc -o ./out/ReverseLink ReverseLink.c

clean:
	rm -rf ./out/*