all: LinkList Delx Delx2 ReversePrint DelMin ReverseLink Sort RangeDelete SearchSame SortPrint Split Split2 DelSame Merge GetCommon Union Match SearchK FindAddr DelAbsSame ChangeList

LinkList: LinkList.c
	gcc -o ./out/LinkList LinkList.c

Delx: Delx.c
	gcc -o ./out/Delx Delx.c

Delx2: Delx2.c
	gcc -o ./out/Delx2 Delx2.c

ReversePrint: ReversePrint.c
	gcc -o ./out/ReversePrint ReversePrint.c

DelMin:  DelMin.c
	gcc -o ./out/DelMin DelMin.c

ReverseLink: ReverseLink.c
	gcc -o ./out/ReverseLink ReverseLink.c

Sort: Sort.c
	gcc -o ./out/Sort Sort.c

RangeDelete: RangeDelete.c
	gcc -o ./out/RangeDelete RangeDelete.c

SearchSame: SearchSame.c
	gcc -o ./out/SearchSame SearchSame.c

SortPrint: SortPrint.c
	gcc -o ./out/SortPrint SortPrint.c

Split: Split.c
	gcc -o ./out/Split Split.c

Split2: Split2.c
	gcc -o ./out/Split2 Split2.c

DelSame: DelSame.c
	gcc -o ./out/DelSame DelSame.c

Merge: Merge.c
	gcc -o ./out/Merge Merge.c

GetCommon: GetCommon.c
	gcc -o ./out/GetCommon GetCommon.c

Union: Union.c
	gcc -o ./out/Union Union.c

Match: Match.c
	gcc -o ./out/Match Match.c

SearchK: SearchK.c
	gcc -o ./out/SearchK SearchK.c

FindAddr: FindAddr.c
	gcc -o ./out/FindAddr FindAddr.c

DelAbsSame: DelAbsSame.c
	gcc -o ./out/DelAbsSame DelAbsSame.c

ChangeList: ChangeList.c
	gcc -o ./out/ChangeList ChangeList.c

clean:
	rm -rf ./out/*