all: Sort DoubleBubbleSort FastMove MinK

Sort: Sort.c 
	gcc Sort.c -o ./out/Sort

DoubleBubbleSort: DoubleBubbleSort.c
	gcc DoubleBubbleSort.c -o ./out/DoubleBubbleSort

FastMove: FastMove.c
	gcc FastMove.c -o ./out/FastMove

MinK: MinK.c
	gcc MinK.c -o ./out/MinK

clean:
	rm -rf ./out/*