all: SequenceList DelMin Reverse DelX DelST DelSame Merge Exchange SearchExchange MSearch Marjority FindMissMin FindMinofTrip

SequenceList: SequenceList.c
	gcc -o ./out/SequenceList SequenceList.c

DelMin: DelMin.c
	gcc -o ./out/DelMin DelMin.c

Reverse: Reverse.c
	gcc -o ./out/Reverse Reverse.c

DelX: DelX.c
	gcc -o ./out/DelX DelX.c

DelST: DelST.c
	gcc -o ./out/DelST DelST.c

DelSame: DelSame.c
	gcc -o ./out/DelSame DelSame.c

Merge: Merge.c
	gcc -o ./out/Merge Merge.c

Exchange: Exchange.c
	gcc -o ./out/Exchange Exchange.c

SearchExchange: SearchExchange.c
	gcc -o ./out/SearchExchange SearchExchange.c

MSearch: MSearch.c
	gcc -o ./out/MSearch MSearch.c

Marjority: Marjority.c
	gcc -o ./out/Marjority Marjority.c

FindMissMin: FindMissMin.c
	gcc -o ./out/FindMissMin FindMissMin.c

FindMinofTrip: FindMinofTrip.c
	gcc -o ./out/FindMinofTrip FindMinofTrip.c


clean:
	rm -rf out/*